version: '2'

services:

  pgadmin:
    image: thajeztah/pgadmin4
    restart: unless-stopped
    volumes:
      - /Users/aperez/src/data/vtv:/data
    ports:
      - "5050:5050"

  postgres:
    image: timescale/timescaledb:0.7.0-pg9.6
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /Users/aperez/src/data/vtv:/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - PGDATA=/data/pg_data

  grafana:
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker-data/grafana/:/var/lib/grafana:z
      - ./docker-data/grafana/log:/var/log/grafana

  influxdb:
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /Users/aperez/src/data:/data
      - ./docker-data/influxdb:/var/lib/influxdb:z
